---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages("reshape")
library(dplyr, warn.conflicts = F)
library(readr)  
library(ggplot2)
library(gmodels)
library(stringr)
library(reshape)

```


```{r}
gastos_gerais = read_csv2(file = "dados//AnoAtual.csv", )

gastos_pb = gastos_gerais %>% select(sgPartido, numAno, numMes, vlrGlosa, txNomeParlamentar, vlrDocumento, txtDescricao, txtFornecedor, vlrLiquido,txtPassageiro, txtTrecho, sgUF, nuDeputadoId, numSubCota) %>% filter(sgUF == "PB")

pb_2016 = gastos_pb %>% filter(numAno == 2016, txtDescricao == "DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.")



divulgacao_2016_por_dep = pb_2016 %>% group_by(txNomeParlamentar, sgPartido) %>% summarise(total=sum(vlrLiquido))

divulgacao_2016_por_dep %>% ggplot(aes(x=reorder(txNomeParlamentar,-total), y=total/1000, fill=sgPartido)) + geom_bar(stat="identity") + geom_text(aes(label=sgPartido)) + coord_flip() + labs(title="Gasto dos Deputados em Divulgação da Atividade Parlamentar", sub="sub-title", x="Deputados", y="Total Gasto em Milhares de Reais")


print(prev_img)
ggsave("prev_img.pdf", width = 6, height = 4) 

```


